name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install

      - name: Prettier
        run: npx prettier --check **/*.{ts,vue,json,html,md,css} --ignore dist/

      - name: Linting
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install

      - name: Build
        run: npx vite build

      - name: Deploy
        # run: npx gh-pages -d dist
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.BEAVER_GITHUB_TOKEN }}
