name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install

      - name: Prettier
        run: npm run prettier --check **/*.{ts,vue,json,html,md,css}

      - name: Linting
        run: npm run lint
